#!/usr/bin/env bash
set -euo pipefail

HOSTS_FILE="/etc/hosts"
START_MARK="# >>> tmux-focus-internet"
END_MARK="# <<< tmux-focus-internet"
REDIRECT_IP="0.0.0.0"

DISTRACTION_DOMAINS=(
    facebook.com www.facebook.com m.facebook.com mbasic.facebook.com messenger.com www.messenger.com
    instagram.com www.instagram.com threads.net www.threads.net
    x.com www.x.com twitter.com www.twitter.com t.co
    tiktok.com www.tiktok.com vm.tiktok.com
    reddit.com www.reddit.com old.reddit.com new.reddit.com
    youtube.com www.youtube.com m.youtube.com youtu.be shorts.youtube.com
    twitch.tv www.twitch.tv kick.com www.kick.com
    netflix.com www.netflix.com disneyplus.com www.disneyplus.com primevideo.com www.primevideo.com
    hulu.com www.hulu.com max.com www.max.com
    discord.com www.discord.com discord.gg canary.discord.com ptb.discord.com
    snapchat.com www.snapchat.com pinterest.com www.pinterest.com
    linkedin.com www.linkedin.com
    whatsapp.com www.whatsapp.com web.whatsapp.com telegram.org web.telegram.org
    news.ycombinator.com
    lequipe.fr www.lequipe.fr
    amazon.com www.amazon.com amazon.fr www.amazon.fr ebay.com www.ebay.com ebay.fr www.ebay.fr
)

DISTRACTION_PROCESSES=(
    Discord discord
    Slack slack
    Telegram telegram-desktop
    WhatsApp whatsapp-for-linux
)

usage() {
    printf 'Usage: %s [on|off|toggle|status]\n' "$(basename "$0")"
}

notify() {
    local message=$1
    if command -v notify-send >/dev/null 2>&1; then
        notify-send "Focus internet" "$message" >/dev/null 2>&1 || true
    fi
    if [ -n "${TMUX:-}" ]; then
        tmux display-message "$message" >/dev/null 2>&1 || true
    fi
    printf '%s\n' "$message"
}

ensure_sudo() {
    if [ "$(id -u)" -eq 0 ]; then
        return
    fi

    sudo -v
}

is_enabled() {
    grep -Fq "$START_MARK" "$HOSTS_FILE"
}

strip_block() {
    awk -v start="$START_MARK" -v end="$END_MARK" '
        $0 == start { blocked = 1; next }
        $0 == end { blocked = 0; next }
        blocked != 1 { print }
    ' "$HOSTS_FILE"
}

install_hosts_file() {
    local tmp=$1

    ensure_sudo
    sudo install -m 0644 -o root -g root "$tmp" "$HOSTS_FILE"
}

flush_dns() {
    if command -v resolvectl >/dev/null 2>&1; then
        sudo resolvectl flush-caches >/dev/null 2>&1 || true
    fi

    if command -v systemd-resolve >/dev/null 2>&1; then
        sudo systemd-resolve --flush-caches >/dev/null 2>&1 || true
    fi

    if command -v nscd >/dev/null 2>&1; then
        sudo systemctl restart nscd >/dev/null 2>&1 || true
    fi
}

close_distraction_apps() {
    for process in "${DISTRACTION_PROCESSES[@]}"; do
        pkill -x "$process" >/dev/null 2>&1 || true
    done
}

enable_focus() {
    local tmp
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' RETURN

    strip_block > "$tmp"
    {
        printf '\n%s\n' "$START_MARK"
        printf '# Generated by ~/.config/scripts/tmux-focus-internet.sh\n'
        for domain in "${DISTRACTION_DOMAINS[@]}"; do
            printf '%s %s\n' "$REDIRECT_IP" "$domain"
            printf ':: %s\n' "$domain"
        done
        printf '%s\n' "$END_MARK"
    } >> "$tmp"

    install_hosts_file "$tmp"
    flush_dns
    close_distraction_apps
    notify "Distractions internet bloquees"
}

disable_focus() {
    local tmp
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' RETURN

    strip_block > "$tmp"
    install_hosts_file "$tmp"
    flush_dns
    notify "Distractions internet debloquees"
}

status_focus() {
    if is_enabled; then
        notify "Focus internet actif"
    else
        notify "Focus internet inactif"
    fi
}

main() {
    local action=${1:-toggle}

    case "$action" in
        on)
            enable_focus
            ;;
        off)
            disable_focus
            ;;
        toggle)
            if is_enabled; then
                disable_focus
            else
                enable_focus
            fi
            ;;
        status)
            status_focus
            ;;
        -h|--help|help)
            usage
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
}

main "$@"
