# i3status configuration file.

general {
        colors = true
        interval = 5
        output_format = "i3bar"
        color_good     = "#afd7af"
        color_degraded = "#d7af87"
        color_bad      = "#d78787"
}

order += "volume master"
order += "cpu_usage"
order += "disk /"
order += "battery all"
order += "tztime local"

volume master {
        format       = "VOL %volume"
        format_muted = "VOL muted"
        device       = "default"
        mixer        = "Master"
        mixer_idx    = 0
}

cpu_usage {
        format        = "CPU %usage"
        max_threshold = 75
}

disk "/" {
        format = "DISK %avail"
}

battery all {
        format        = "BAT %percentage"
        format_down   = ""
        status_chr    = "CHR"
        status_bat    = "BAT"
        status_full   = "FULL"
        status_unk    = "UNK"
        path          = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 15
}

tztime local {
        format = "%d %b  %H:%M"
}
